"""a

Revision ID: 2b81d0790f10
Revises: f7006424e5cd
Create Date: 2025-05-08 21:56:08.485113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b81d0790f10'
down_revision = 'f7006424e5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('pixel_red', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pixel_green', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pixel_blue', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='image_data_pkey')
    )
    # ### end Alembic commands ###
