"""empty message

Revision ID: 6539f86c2e95
Revises: 933b2e7bc7d8
Create Date: 2023-05-13 09:52:54.011708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6539f86c2e95'
down_revision = '933b2e7bc7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.drop_column('mode_time')

    # ### end Alembic commands ###
