"""Regenerar migraciones

Revision ID: 7d50f8ce1dd1
Revises: 1920d7e9c1dc
Create Date: 2025-05-08 17:11:06.789172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d50f8ce1dd1'
down_revision = '1920d7e9c1dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_red', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pixel_green', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pixel_blue', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('upload_time', sa.DateTime(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('pixel_data')
        batch_op.drop_column('upload_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pixel_data', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('upload_time')
        batch_op.drop_column('pixel_blue')
        batch_op.drop_column('pixel_green')
        batch_op.drop_column('pixel_red')

    # ### end Alembic commands ###
