"""empty message

Revision ID: 933b2e7bc7d8
Revises: 2e9a0123d6e2
Create Date: 2023-05-12 17:44:44.067842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933b2e7bc7d8'
down_revision = '2e9a0123d6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secret', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret')
    )
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('device')
    # ### end Alembic commands ###
