"""b

Revision ID: e95f32cb7145
Revises: 2b81d0790f10
Create Date: 2025-05-08 22:07:14.980769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95f32cb7145'
down_revision = '2b81d0790f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('pixel_red', sa.Integer(), nullable=False),
    sa.Column('pixel_green', sa.Integer(), nullable=False),
    sa.Column('pixel_blue', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_data')
    # ### end Alembic commands ###
